add ci
rtest12/angular-react-starter pull request #2
Opened 2023-02-04 19:54 UTC by rtest12

2023-02-07 04:05 UTC, dmitry-mightydevops requested changes

2023-02-07 04:05 UTC, dmitry-mightydevops commented on .github/workflows/ci.yml
> +
Let's reduce number of copy paster.
1. Clone repo
2. Setup npm 
3. then run tests
4. if succeed - then build and push

Let's reduce the execution time to a minimum.


an idea:
```
jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t foo/bar:$GITHUB_SHA
          mkdir -p path/to/artifacts
          docker save foo/bar:$GITHUB_SHA > path/to/artifacts/docker-image.tar
          
      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: path/to/artifacts
          retention-days: 1

  docker-deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: path/to/artifacts

      - name: Docker load
        run: |
          cd path/to/artifacts
          docker load < docker-image.tar
          # docker_build_push.sh
```
https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs

2023-02-07 04:05 UTC, dmitry-mightydevops commented on .github/workflows/ci.yml
> +          to: ${{secrets.MAIL_USERNAME}}
should be the author of the commit, not hardcoded value from secrets

2023-02-07 04:06 UTC, dmitry-mightydevops commented
@rtest12 also - do you have docker-compose.yaml to review?

2023-02-08 03:44 UTC, dmitry-mightydevops commented
@rtest12 when you done:
- add label "Needs Review" to your PR
- re-request me as reviewer
- remove the PR from the "draft" status

Otherwise I don't know if you still have work in propgress, or finished changes requested and ready for another review

2023-02-09 04:22 UTC, dmitry-mightydevops commented
@rtest12 you also need to re-request the review
![image](https://user-images.githubusercontent.com/70822710/217717186-6b13dea8-3f8d-4dfd-bf73-34d96cdbdad3.png)

click on the () icon on the left from the red icon

2023-02-09 04:30 UTC, dmitry-mightydevops commented on .github/workflows/ci.yml
> +            if: failure()
this is cryptic. You need to reference the step by ID to check if it was successful or failed.

2023-02-09 04:30 UTC, dmitry-mightydevops commented on nginx.conf
> +            try_files $uri $uri/ =404;
your soluton using deny all is not fixing the problem on line 38. Your security hole is still there. If in the future someone removes lines 33-35 or make error in regexp - anyone can download files there were not supposed to.

Pls read official docs how to use try_files, and what is the purpose of passing $uri $uri/ =404; args.
http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

2023-02-09 04:30 UTC, dmitry-mightydevops commented on .github/workflows/ci.yml
> +          to: ${{secrets.MAIL_USERNAME}}
@rtest12 I don't see this is fixed. Still `to: ${{secrets.MAIL_USERNAME}}`

2023-02-09 04:30 UTC, dmitry-mightydevops requested changes
see my feedback

2023-02-10 02:39 UTC, dmitry-mightydevops requested changes

2023-02-10 02:39 UTC, dmitry-mightydevops commented on .github/workflows/ci.yml
> +              to: omelchenko.sochi@gmail.com
it should not be hardcoded this way either :)
see variables that github makes it available inside github action run for each build - use the author of the commit. So If I commit into your repo - I (as the author) should receive it, not you.

2023-02-10 02:39 UTC, dmitry-mightydevops commented on nginx.conf
>      }
so this is a little bit closer :)  but still not perfect.

**hint**:  use index.html inside try_files and pass query args as needed.

That way you don't depend on the value in $uri and don't need regexp in location.

2023-02-14 01:31 UTC, dmitry-mightydevops approved these changes
@rtest12 
Макс - проапрувил. Сделаем на след. неделе групповой митинг с ребятами, что прошли тест и обсудим

- дату старта практики
- процесс
- что нужно будет иметь к началу практики

Марина отправит уведомление.

2023-02-14 09:13 UTC, rtest12 commented
> @rtest12 Макс - проапрувил. Сделаем на след. неделе групповой митинг с ребятами, что прошли тест и обсудим
> 
>     * дату старта практики
> 
>     * процесс
> 
>     * что нужно будет иметь к началу практики
> 
> 
> Марина отправит уведомление.

Хорошо, буду на связи.

2023-12-18 13:27 UTC, closed without merging